from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv
from server.parse_code import parse_single_file,parse_code_directory
import json
from pathlib import Path
import os
from langgraph.graph import StateGraph, MessagesState, END
from langgraph.types import Command
from pydantic import BaseModel, Field
from typing import Literal

load_dotenv()

class AgentState(MessagesState):
    count: int

llm=ChatGoogleGenerativeAI(model="gemini-2.5-flash")

generator_prompt=ChatPromptTemplate([
    ("system","""You are a documentation generator agent responsible for making documentations for
    python scripts. You will be given a json file that contains the information
    regarding the different functions, class, methods used in the script,
    and their docstrings. Use it to write a clean Markdown description,
    explain its parameters, and provide a usage example as well.
    IMPORTANT:
    1. The style of the documentation should be in the style of GitHub documentation.
    2. Return only the content of the documentation."""),
    MessagesPlaceholder(variable_name="messages")
])

class vallidator_content(BaseModel):
    strengths:str=Field(description="The good elements in the documentation. The areas to preserve.")
    weakness:str=Field(description="The bad elements in the documentation. The areas to to improve.")
    status:Literal["approved", "not approved"]=Field(description="""Indicated if the documentation needs changes or not. It can have two values
    1. approved: If the vallidator agent thinks the documentation is perfect.
    1. not approved: If the vallidator agent thinks the documentation needs imporvement""")

class content(BaseModel):
    content:str=Field(description="This the the final documentation")

vallidator_prompt=ChatPromptTemplate([
    ("system","""You are an vallidator agent responsible for vallidating the documentation generated by another AI for a python Script. Your
    duty is to go through the documentation point out the areas of weakness and strength, so that necessary changes can be made.
    If you think the documentation is perfect then dont mention any changes."""),
    MessagesPlaceholder(variable_name="messages")
])

modifier_prompt=ChatPromptTemplate([
    ("system","""You are Documentation modifier. Your duty is to modify the generated documentation accordin to the suggestions mentioned by the user."""),
    MessagesPlaceholder(variable_name="messages")
])

finalizer_prompt=ChatPromptTemplate([
    ("system","""You are Documentation vallidator, who vallidates the documents before finalizing. 
    Your duty is to strip away unwanted text and only return the document content. Since the document is generated by AI it might contain 
    AI texts in the begining, in the end and here and there. Your job is to ONLY output the cotent of the documentation, which can be directly copy pasted."""),
    MessagesPlaceholder(variable_name="messages")
])

vallidator_chain=vallidator_prompt | llm.with_structured_output(schema=vallidator_content)
modifier_chain=modifier_prompt | llm

def generator_node(state):
    generator_chain=generator_prompt | llm
    response = generator_chain.invoke(state)
    return Command(
        update={"messages":response},
        goto="vallidator"
    )

def vallidator_node(state):
    response = vallidator_chain.invoke(state)

    current_count = state.get("count", 0) + 1

    if response.status=="approved" or current_count>1:
        return Command(
            goto="Finalizer"
        )
    else:
        analysis=f"The analysis of the documentation are as follows:\nAras to preserve:\n{response.strengths}\n\nAreas to improve:\n{response.weakness}"
        return Command(
            update={"messages":HumanMessage(content=analysis),"count": current_count},
            goto="modifier"
        )

def modifier_node(state):
    response = modifier_chain.invoke(state)
    return Command(
        update={"messages":response},
        goto="vallidator"
        )

def finalizer_node(state):
    # documentation=state[-1]
    finalizer_chain=finalizer_prompt | llm.with_structured_output(schema=content)
    finalized_document=finalizer_chain.invoke(state)
    return Command(
        update={"messages":finalized_document},
        goto=END
    )

graph=StateGraph(AgentState)


graph.add_node("generator",generator_node)
graph.add_node("vallidator",vallidator_node)
graph.add_node("modifier",modifier_node)
graph.add_node("finalizer",finalizer_node)

graph.set_entry_point("generator")

agent=graph.compile()


def generate_doc(input):
    documentation = agent.invoke({"messages": [HumanMessage(content=input)], "count": 0})
    return documentation

if __name__ == "__main__":
    result = parse_single_file(file_path="./server/parse_code.py")
    result=json.dumps(result, indent=4)
    response = generate_doc(input=result)
    print(f"{response}\n\n\n")
    print(response["messages"][-1])


    output_path = Path("./docs/README.md")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(response['messages'][-1].content, encoding="utf-8")

    print(f"Documentation successfully saved to {output_path}")
